{{ $namespace := default dict .Values.namespace }}
{{ $app_name := default .Chart.Name .Values.app_name }}
{{ $secrets := default dict .Values.secrets }}
{{ $global := default dict .Values.global }}
{{ $global_annotations := default (list) $global.annotations }}
{{ $annotations := default (list) .Values.annotations }}
{{ $global_labels := default (list) $global.labels }}
{{ $resource_annotations := default (list) $secrets.annotations }}
{{ $resource_labels := default (list) $secrets.labels }}
{{- /* Default values for common apps */ -}}
{{- if $app_name | eq "postgres" }}
  {{ $secrets := .Values.secrets | default (list (dict "key" "PGDATA" "value" "/opt/apps/pgsql/data/data/pgdata") (dict "key" "POSTGRES_PASSWORD" "value" "postgres") (dict "key" "POSTGRES_USERNAME" "value" "postgres")) }}
{{- else if $app_name | eq "cassandra" }}
  {{ $secrets := .Values.secrets | default (list (dict "key" "HEAP_NEWSIZE" "value" "128M") (dict "key" "MAX_HEAP_SIZE" "value" "2G") (dict "key" "CASSANDRA_DC" "value" "DC1") (dict "key" "CASSANDRA_ENDPOINT_SNITCH" "value" "GossipingPropertyFileSnitch")) }}
{{- else if $app_name | eq "kafka" }}
  {{ $secrets := .Values.secrets | default (list (dict "key" "DATA" "value" "/home/kafka/zk_data")) }}
{{- else if $app_name | eq "neo4j" }}
  {{ $secrets := .Values.secrets | default (list (dict "key" "NEO4J_PLUGINS" "value" "[\"graph-data-science\", \"apoc\"]") (dict "key" "NEO4J_server_config_strict__validation_enabled" "value" "false") (dict "key" "NEO4J_AUTH" "value" "neo4j/changeit") (dict "key" "NEO4J_ACCEPT_LICENSE_AGREEMENT" "value" "yes")) }}
{{- end }}
{{- /* ---------------------------- */ -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ $app_name }}-secrets
  namespace: {{ default .Release.Name $namespace.name }}
  labels:
    app: {{ $app_name }}
    {{- range $label := .Values.labels }}
    {{ $label.name }}: {{ $label.value }}
    {{- end }}
    {{- range $label := $global_labels }}
    {{ $label.name }}: {{ $label.value }}
    {{- end }}
    {{- range $label := $resource_labels }}
    {{ $label.name }}: {{ $label.value }}
    {{- end }}
  {{- if or $global_annotations $resource_annotations $annotations }}
  annotations:
    {{- range $annotation := $global_annotations }}
    {{ $annotation.key }}: {{ $annotation.value | quote }}
    {{- end }}
    {{- range $annotation := $resource_annotations }}
    {{ $annotation.key }}: {{ $annotation.value | quote }}
    {{- end }}
    {{- range $annotation := $annotations }}
    {{ $annotation.key }}: {{ $annotation.value | quote }}
    {{- end }}
  {{- end }}
data:
  {{- range $secrets }}
  {{ .key }}: {{ .value | b64enc | quote }}
  {{- end }}
