{{ $namespace := default dict .Values.namespace }}
{{ $app_name := default .Chart.Name .Values.app_name }}
{{ $service := default dict .Values.service }}
{{ $service_port := $service.port }}
{{ $global := default dict .Values.global }}
{{ $global_annotations := default (list) $global.annotations }}
{{ $annotations := default (list) .Values.annotations }}
{{ $global_labels := default (list) $global.labels }}
{{ $resource_annotations := default (list) $service.annotations }}
{{ $resource_labels := default (list) $service.labels }}
{{- /* Default values for common apps */ -}}
{{- if $app_name | eq "postgres" }}
  {{ $service_port := $service.port | default 5432 }}
{{- else if $app_name | eq "cassandra" }}
  {{ $service_port := $service.port | default 9042 }}
{{- else if $app_name | eq "kafka" }}
  {{ $service_port := $service.port | default 9092 }}
{{- else if $app_name | eq "neo4j" }}
  {{ $service_port := $service.port | default 7474 }}
{{- end }}
{{- /* ---------------------------- */ -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $app_name }}-service
  namespace: {{ default .Release.Name $namespace.name }}
  labels:
    app: {{ $app_name }}
    {{- range $label := .Values.labels }}
    {{ $label.name }}: {{ $label.value }}
    {{- end }}
    {{- range $label := $global_labels }}
    {{ $label.name }}: {{ $label.value }}
    {{- end }}
    {{- range $label := $resource_labels }}
    {{ $label.name }}: {{ $label.value }}
    {{- end }}
  {{- if or $global_annotations $resource_annotations $annotations }}
  annotations:
    {{- range $annotation := $global_annotations }}
    {{ $annotation.key }}: {{ $annotation.value | quote }}
    {{- end }}
    {{- range $annotation := $resource_annotations }}
    {{ $annotation.key }}: {{ $annotation.value | quote }}
    {{- end }}
    {{- range $annotation := $annotations }}
    {{ $annotation.key }}: {{ $annotation.value | quote }}
    {{- end }}
  {{- end }}
spec:
  type: 
  ports:
  - port: {{ $service_port }}
    targetPort: {{ $service_port }}
    protocol: TCP
    name: {{ $app_name }}-port
  selector:
    app: {{ $app_name }}