apiVersion: v2
name: generic-db
description: Example Helm chart that deploys a generic database, such as PostgreSQL, Cassandra, or Neo4j, on Kubernetes.
type: application
version: 1.1.7
appVersion: "1.0"
