apiVersion: v2
name: fabric-space-generic
description: The following Helm Chart Deploys Fabric and Generic DB

type: application
version: 1.1.8
appVersion: "8.2"

dependencies:
  - name: fabric
    version: ">=1.2.0"
    repository: "file://./charts/fabric"
    condition: fabric.enabled
  - name: generic-db
    alias: postgres
    version: ">=1.0.2"
    repository: "file://./charts/generic-db"
    condition: postgres.enabled
  - name: generic-db
    alias: cassandra
    version: ">=1.0.2"
    repository: "file://./charts/generic-db"
    condition: cassandra.enabled
  - name: generic-db
    alias: kafka
    version: ">=1.0.2"
    repository: "file://./charts/generic-db"
    condition: kafka.enabled
  - name: generic-db
    alias: neo4j
    version: ">=1.0.2"
    repository: "file://./charts/generic-db"
    condition: neo4j.enabled
